# Generated by Django 2.2.24 on 2021-11-24 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0014_mobilepayment_nullable_customername_20210908_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[^(\\/\\\\)]+')]),
        ),
    ]
